device: set __opened_files before calling the super constructor
We remove files in __opened_files on __del__ and that is called if super()
fails with a exception handled elsehwere. Fixes:
  AttributeError: 'AppleKeyboard' object has no attribute '_opened_files'

Signed-off-by: Peter Hutterer <peter.hutterer@who-t.net>